### PR TITLE
Add support for Oracle 12 limit/offset syntax

### PR DESCRIPTION
**Pull request by timon**
This adds support for `OFFSET o ROWS FETCH NEXT l ROWS ONLY` syntax introduced in Oracle 12c database

### CODE REVIEW

**Comment by timon** [comment]
@jeremyevans I have reverted change that split `select_sql` into several methods.
Could you please review?

**Comment by jeremyevans** [comment]
Yep, this is what I had in mind.  I'll try to setup an Oracle 12 VM and see if I can test this.  I'll try to get it tested and merged before the next Sequel release.

**Comment by timon** [comment]
@jeremyevans perhaps I should reopen PR using your repository's master as base branch?

**Comment by jeremyevans** [comment]
That shouldn't be necessary, we can always rebase it before merging.

**Pull request merged**
